### ISSUE TITLE
Non alpha character replaced with null character instead of removed

### ISSUE THREAD

**Issue by bondxf** [vladimirvivien/learning-go#3]
https://github.com/vladimirvivien/learning-go/blob/b39c8264ff3c8c7704a2699bc474bd38896896c0/tutorial/io/alpha_reader.go#L44

**Comment by bondxf** [comment]
Sorry, not really an issue.

**Comment by K1ngjulien** [comment]
@vladimirvivien why is this not an issue? I've been trying to understand this for like an hour :sweat_smile: 

Is it because string(buf) removes all the nulls inside anyway?

**Comment by vladimirvivien** [comment]
@K1ngjulien not sure about the detail of this issue.
Let me know if you have a specific question about hat code.
(`string(buf)` does not remove any thing as far as I know)
